#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

echo "================================================================="
echo "  Voice-Enabled Indic RAG — Environment & Stack Setup"
echo "  (HH Goa 2026, Task #2)"
echo "================================================================="
echo "==> Project Root: $PROJECT_ROOT"

# 1. Check / Install uv Package Manager
if ! command -v uv &> /dev/null; then
    echo "==> [1/7] uv not found, installing via official installer..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
else
    echo "==> [1/7] uv package manager detected: $(uv --version)"
fi

# 2. System Audio Dependencies Diagnostic
echo "==> [2/7] Checking system audio libraries..."
MISSING_SYS_DEPS=()
if ! ldconfig -p 2>/dev/null | grep -q libportaudio; then
    if [ ! -f /usr/lib/x86_64-linux-gnu/libportaudio.so.2 ] && [ ! -f /usr/local/lib/libportaudio.so ]; then
        MISSING_SYS_DEPS+=("libportaudio2 / portaudio19-dev")
    fi
fi
if ! command -v ffmpeg &> /dev/null; then
    MISSING_SYS_DEPS+=("ffmpeg")
fi

if [ ${#MISSING_SYS_DEPS[@]} -gt 0 ]; then
    echo "    ℹ️  Recommended system audio libraries: ${MISSING_SYS_DEPS[*]}"
    echo "    To install on Ubuntu/Debian: sudo apt-get update && sudo apt-get install -y libportaudio2 portaudio19-dev libsndfile1 ffmpeg"
    echo "    To install on macOS: brew install portaudio libsndfile ffmpeg"
fi

# 3. Synchronize Python Environment and Stack Dependencies
echo "==> [3/7] Syncing Python dependencies via 'uv sync'..."
uv sync

# 4. Environment & API Keys Template Setup
echo "==> [4/7] Configuring environment files..."
if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        echo "    ✓ Created .env from .env.example (Insert your SARVAM_API_KEY / ELEVENLABS_API_KEY if needed)"
    fi
else
    echo "    ✓ Existing .env found."
fi

# 5. Hardware Acceleration & CUDA Configuration
echo "==> [5/7] Detecting hardware accelerators (GPU / CUDA)..."
CUDA_AVAILABLE=false
if command -v nvidia-smi &> /dev/null && nvidia-smi -L &> /dev/null; then
    echo "    ✓ NVIDIA GPU detected:"
    nvidia-smi -L | sed 's/^/      /'
    WHISPER_DEVICE="cuda"
    WHISPER_COMPUTE_TYPE="int8" # int8 quantization for sub-200ms latency budget
    RETRIEVAL_DEVICE="cuda"
    CUDA_AVAILABLE=true
else
    echo "    ℹ️  No NVIDIA GPU detected. Configuring CPU execution with int8 quantization..."
    WHISPER_DEVICE="cpu"
    WHISPER_COMPUTE_TYPE="int8"
    RETRIEVAL_DEVICE="cpu"
fi

cat > .env.runtime <<EOF
# Auto-generated by setup.sh on $(date)
WHISPER_MODEL=tiny
WHISPER_DEVICE=${WHISPER_DEVICE}
WHISPER_COMPUTE_TYPE=${WHISPER_COMPUTE_TYPE}
RETRIEVAL_DEVICE=${RETRIEVAL_DEVICE}
EOF
echo "    ✓ Wrote hardware configuration to .env.runtime"

# 6. Pre-download and Warm-up AI Models
echo "==> [6/7] Pre-caching and warming up AI models..."

# Warmup STT faster-whisper model
uv run python - <<'PYEOF'
import os
import sys

device = os.environ.get("WHISPER_DEVICE", "cpu")
compute_type = os.environ.get("WHISPER_COMPUTE_TYPE", "int8")

print(f"    • Warming up STT faster-whisper (tiny) on {device} ({compute_type})...")
try:
    from faster_whisper import WhisperModel
    model = WhisperModel("tiny", device=device, compute_type=compute_type)
    print("      ✓ Faster-Whisper tiny cached successfully.")
except Exception as e:
    if device != "cpu":
        print(f"      ⚠️ GPU load failed ({e}), falling back to CPU...")
        from faster_whisper import WhisperModel
        model = WhisperModel("tiny", device="cpu", compute_type="int8")
        print("      ✓ Faster-Whisper tiny cached on CPU.")
    else:
        print(f"      ⚠️ Warning during Whisper cache: {e}")
PYEOF

# Warmup Multilingual E5 Embeddings
uv run python - <<'PYEOF'
print("    • Pre-caching Multilingual-E5 Embedder (intfloat/multilingual-e5-small)...")
try:
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer("intfloat/multilingual-e5-small")
    print("      ✓ multilingual-e5-small cached successfully.")
except Exception as e:
    print(f"      ℹ️ Trying transformers download: {e}")
    from transformers import AutoModel, AutoTokenizer
    AutoModel.from_pretrained("intfloat/multilingual-e5-small")
    AutoTokenizer.from_pretrained("intfloat/multilingual-e5-small")
    print("      ✓ Model and Tokenizer downloaded.")
PYEOF

# 7. Check / Bootstrap FAISS Vector Index and Audio Diagnostics
echo "==> [7/7] Checking Vector Index & Audio Input Devices..."
uv run python - <<'PYEOF'
from pathlib import Path
import os

index_path = Path("data/processed/faiss_index.bin")
meta_path = Path("data/processed/passage_metadata.json")

if not (index_path.exists() and meta_path.exists()):
    print("    • Vector index not found. Building bootstrap FAISS index from MSMARCO-XI dataset...")
    try:
        from src.retrieval.embedder import MultilingualE5Embedder
        from benchmarks.run_latency_bench import ensure_index_exists
        device = os.environ.get("RETRIEVAL_DEVICE", "cpu")
        embedder = MultilingualE5Embedder(model_name_or_path="intfloat/multilingual-e5-small", device=device, warmup=True)
        ensure_index_exists(embedder, str(index_path), str(meta_path))
        print("      ✓ FAISS index and metadata bootstrapped successfully.")
    except Exception as e:
        print(f"      ⚠️ Could not bootstrap index automatically: {e}")
else:
    print(f"    ✓ FAISS vector index verified at {index_path}")

# Audio device diagnostics
try:
    from src.stt.live_capture import list_audio_input_devices
    devices = list_audio_input_devices()
    if devices:
        print(f"    ✓ Detected {len(devices)} active microphone device(s). Ready for live voice commands.")
    else:
        print("    ℹ️  No active microphones detected. (File upload & text modes remain fully operational).")
except Exception as e:
    print(f"    ℹ️  Audio query info: {e}")
PYEOF

echo ""
echo "================================================================="
echo "✓ Setup Complete! All components are installed and warmed up."
echo ""
echo "Quick Commands to run:"
echo "  1. Live Voice Command Mode:      ./run.sh --live"
echo "  2. Live Web Application UI:      ./run.sh --server (http://localhost:7860)"
echo "  3. Query from Audio File:        ./run.sh --file data/sample_voice_query.wav"
echo "  4. Direct Text Query:            ./run.sh --text \"भारत की राजधानी क्या है?\""
echo "  5. Sub-200ms Latency Benchmarks: ./run.sh --bench"
echo "  6. Run Automated Test Suite:     ./run.sh --test"
echo "================================================================="

